name: Update Homebrew Cask for Dorion

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:     # Allows manual triggering of the workflow

jobs:
  update_cask:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0 # Set the appropriate Ruby version for your environment

    - name: Get latest release info
      id: release
      run: |
        latest_release=$(curl --silent "https://api.github.com/repos/SpikeHD/Dorion/releases/latest")
        version=$(echo "$latest_release" | jq -r .tag_name)
        download_x64=$(echo "$latest_release" | jq -r '.assets[] | select(.name | contains("x64.dmg")).browser_download_url')
        download_arm=$(echo "$latest_release" | jq -r '.assets[] | select(.name | contains("aarch64.dmg")).browser_download_url')
        echo "version=$version" >> $GITHUB_ENV
        echo "download_x64=$download_x64" >> $GITHUB_ENV
        echo "download_arm=$download_arm" >> $GITHUB_ENV

    - name: Calculate SHA256 for x64 dmg
      run: |
        curl -L -o Dorion_x64.dmg "$download_x64"
        sha256_x64=$(shasum -a 256 Dorion_x64.dmg | cut -d " " -f 1)
        echo "sha256_x64=$sha256_x64" >> $GITHUB_ENV

    - name: Calculate SHA256 for aarch64 dmg
      run: |
        curl -L -o Dorion_aarch64.dmg "$download_arm"
        sha256_arm=$(shasum -a 256 Dorion_aarch64.dmg | cut -d " " -f 1)
        echo "sha256_arm=$sha256_arm" >> $GITHUB_ENV

    - name: Update Cask formula
      run: |
        version=${{ env.version }}
        sha256_x64=${{ env.sha256_x64 }}
        sha256_arm=${{ env.sha256_arm }}
        # Update version, urls, and sha256 in the formula
        sed -i '' "s/version \".*\"/version \"$version\"/" Casks/dorion.rb
        sed -i '' "s/sha256 \".*\"/sha256 \"$sha256_x64\"/" Casks/dorion.rb
        sed -i '' "s/sha256 \".*\"/sha256 \"$sha256_arm\"/" Casks/dorion.rb
        sed -i '' "s|url \".*\"|url \"$download_x64\"|" Casks/dorion.rb
        sed -i '' "s|url \".*\"|url \"$download_arm\"|" Casks/dorion.rb

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@github.com"
        git add Casks/dorion.rb
        git commit -m "Update Dorion Cask to version $version"
        git push

    - name: Create a Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Update Dorion Cask to version ${{ env.version }}"
        branch: "auto-update-cask"
        title: "Update Dorion Cask to version ${{ env.version }}"
        body: "This PR updates Dorion to version ${{ env.version }}."
