name: Homebrew Cask Auto-update

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger of the action

jobs:
  livecheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Homebrew, check and update
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew tap psharma04/dorion
        cd /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/psharma04/homebrew-dorion
        NEW_VERSION=$(brew livecheck dorion --newer-only --json | jq -r '.[0].version.latest')
        CURRENT_VERSION=$(grep -E '^  version' Casks/dorion.rb | awk '{print $2}' | tr -d '"')

        if [ "$NEW_VERSION" != "null" ]; then
          # Print the change in versions
          brew livecheck dorion
          # Update the version in the cask file
          sed -i "s/$CURRENT_VERSION/$NEW_VERSION/g" Casks/dorion.rb

          # Commit and push the changes directly to the main branch
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git checkout main
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git add Casks/dorion.rb
          git commit -m "Update Dorion cask to $NEW_VERSION"
          git push origin main
        else
          echo "No new version found"
        fi
